# site settings
title: ProjectStar
subtitle: by Jacob Mellichamp
email: jakemellichamp@gmail.com
description: Computer Scientist | Cyber Analyst
baseurl: ""
url: http://projectstar.io
author: Jacob Mellichamp
street_address: 
city: Charleston  
state: SC
zip_code: 
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://gitlab.com/Jacob-Mellichamp
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/jakemelli
linkedin_url: https://www.linkedin.com/in/jake-mellichamp
pinterest_url:
slack_url:

# build settings
markdown: kramdown

sass:
  style: compressed
